# import turtle
# b=turtle.Screen()
# b.bgcolor("pink")
# t=turtle.Turtle()
# t.shape("circle")
# t.shapesize(2)
# t.color("red","pink")
# t.pensize(10)
# t.speed(6)
# t.forward(100)
# t.left(90)
# t.forward(100)
# t.left(90)
# t.forward(100)
# t.left(90)
# t.forward(100)
# t.left(90)
# t.clear()
# turtle.done()
# turtle.mainloop()

# from turtle import *
# root=Screen()
# trt=Turtle()
# trt.dot(20)
# for i in range(7):
#     trt.forward(100)
#     trt.left(51.42)
# mainloop()

# import turtle
# t=turtle.Turtle()
# t.up()
# t.goto(-190,100)
# t.down()
# t.circle(60)
# t.up()
# t.goto(190,100)
# t.down()
# t.circle(60)
# t.up()
# t.goto(0,-5)
# t.down()
# t.circle(60)
# t.up()
# t.goto(-190,-150)
# t.down()
# t.circle(60)
# t.up()
# t.goto(190,-150)
# t.down()
# t.circle(60)


# turtle.done()

